stages:
  - pytest
  - functional_test

default:
  image: centos:8

variables:
  GECKODRIVER_VERSION: "0.24.0"
  PYTHON_VERSION: "python36"
  DJANGO_LOG_LEVEL: "INFO"

gecko:
  stage: functional_test
  before_script:
    - yum group install -y "Development Tools"
    - yum install -y ${PYTHON_VERSION}-devel ${PYTHON_VERSION}-pip firefox scl-utils
    - yum install -y http://www6.atomicorp.com/channels/atomic/centos/7/x86_64/RPMS/atomic-heimdal-runtime-7.5.0-8.el7.x86_64.rpm
    - yum install -y http://www6.atomicorp.com/channels/atomic/centos/7/x86_64/RPMS/atomic-sqlite-3.8.5-6803.el7.art.x86_64.rpm
    - cp /opt/atomicorp/atomic/root/usr/bin/sqlite3 /usr/bin/
    - cp /opt/atomicorp/atomic/root/usr/lib64/* /usr/lib64/
    - which sqlite3
    - curl -L -O https://github.com/mozilla/geckodriver/releases/download/v${GECKODRIVER_VERSION}/geckodriver-v${GECKODRIVER_VERSION}-linux64.tar.gz
    - tar xf geckodriver-v${GECKODRIVER_VERSION}-linux64.tar.gz -C /usr/local/bin
    - chmod +x /usr/local/bin/geckodriver
    - python3 setup.py install
    - DJANGO_SETTINGS_MODULE=eZeeKonfigurator.settings.development python3 manage.py runserver 1>&2 &
    - bash -c "until curl -s http://localhost:8000; do sleep 1; done"
  script:
    - python3 eZeeKonfigurator/functional_tests.py

pytest:
  stage: pytest
  before_script:
    - yum group install -y "Development Tools"
    - yum install -y ${PYTHON_VERSION} ${PYTHON_VERSION}-devel
    - python3 -m venv test_env
    - test_env/bin/python3 -m pip install --upgrade pip setuptools wheel
    - test_env/bin/python3 setup.py install
  script:
    - DJANGO_SETTINGS_MODULE=eZeeKonfigurator.settings.development test_env/bin/python3 manage.py test