image: docker:19.03.12

variables:
  GITLAB_FEATURES: "container_scanning"
  ESNET_REGISTRY: "hub.es.net:5000/esnet/ezk"

stages:
  - build_docker
  - unit_test
  - integration_test
  - functional_test

build_docker:
  stage: build_docker
  before_script:
      - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

  script:
      - docker pull ${CI_REGISTRY_IMAGE}/ezk:latest || true
      - docker build --cache-from ${CI_REGISTRY_IMAGE}/ezk:latest --tag ${CI_REGISTRY_IMAGE}/ezk:latest --target ezk .
      - docker push ${CI_REGISTRY_IMAGE}/ezk:latest

      - docker pull ${CI_REGISTRY_IMAGE}/ezk_test:latest || true
      - docker build --cache-from ${CI_REGISTRY_IMAGE}/ezk_test:latest --tag ${CI_REGISTRY_IMAGE}/ezk_test:latest --target ezk_test .
      - docker push ${CI_REGISTRY_IMAGE}/ezk_test:latest


unit_test:
  stage: unit_test
  image: ${CI_REGISTRY_IMAGE}/ezk:latest
  script:
    - cd /app; venv/bin/python3 manage.py test webconfig.tests.test_models

conversion_test:
  stage: integration_test
  image: ${CI_REGISTRY_IMAGE}/ezk_test:latest
  script:
    - cd /app; venv/bin/python3 manage.py test webconfig.tests.test_broker_posts

gecko:
  stage: functional_test
  image: ${CI_REGISTRY_IMAGE}/ezk_test:latest
  before_script:
    - cd /app; venv/bin/python3 manage.py runserver --settings eZeeKonfigurator.settings.development &
    - sleep 5
  script:
    - cd /app; venv/bin/python3 eZeeKonfigurator/functional_tests.py

