image: docker:19.03.12

variables:
  GITLAB_FEATURES: "container_scanning"
  ESNET_REGISTRY: "hub.es.net:5000/esnet/ezk"

stages:
  - build_docker
  - unit_test
  - functional_test

build_docker:
  stage: build_docker
  before_script:
      - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

  script:
      - docker pull ${CI_REGISTRY_IMAGE}/ezk_runtime:latest || true
      - docker build --cache-from ${CI_REGISTRY_IMAGE}/ezk_runtime:latest --tag ${CI_REGISTRY_IMAGE}/ezk_runtime:latest --target ezk_runtime .
      - docker push ${CI_REGISTRY_IMAGE}/ezk_runtime:latest

      - docker pull ${CI_REGISTRY_IMAGE}/ezk_gecko:latest || true
      - docker build --cache-from ${CI_REGISTRY_IMAGE}/ezk_gecko:latest --tag ${CI_REGISTRY_IMAGE}/ezk_gecko:latest --target ezk_gecko .
      - docker push ${CI_REGISTRY_IMAGE}/ezk_gecko:latest


pytest:
  stage: unit_test
  image: ${CI_REGISTRY_IMAGE}/ezk_runtime:latest
  script:
    - venv/bin/python3 manage.py test

gecko:
  stage: functional_test
  image: ${CI_REGISTRY_IMAGE}/ezk_gecko:latest
  before_script:
    - venv/bin/python3 manage.py runserver --settings eZeeKonfigurator.settings.development &
    - sleep 5
  script:
    - venv/bin/python3 eZeeKonfigurator/functional_tests.py

