stages:
  - functional_test
  - pytest

default:
  image: centos:8

variables:
  GECKODRIVER_VERSION: "0.24.0"
  PYTHON_VERSION: "python36"
  DJANGO_LOG_LEVEL: "INFO"

gecko:
  stage: functional_test
  before_script:
    - ip addr list
    - yum group install -y "Development Tools"
    - curl https://download.opensuse.org/repositories/security:/zeek/CentOS_8/security:zeek.repo -o /etc/yum.repos.d/zeek.repo
    - yum install -y ${PYTHON_VERSION}-devel ${PYTHON_VERSION} firefox scl-utils zeekctl sqlite net-tools
    - python3 -m pip install --upgrade pip setuptools wheel
    - curl -L -O https://github.com/mozilla/geckodriver/releases/download/v${GECKODRIVER_VERSION}/geckodriver-v${GECKODRIVER_VERSION}-linux64.tar.gz
    - tar xf geckodriver-v${GECKODRIVER_VERSION}-linux64.tar.gz -C /usr/local/bin
    - chmod +x /usr/local/bin/geckodriver
    - python3 setup.py install
    - python3 manage.py runserver --settings eZeeKonfigurator.settings.development -v 3
    - sleep 5
    - netstat -tlnp
    - bash -c "until curl -sv http://localhost:8000; do sleep 1; done"
  script:
    - PATH=/opt/zeek/bin:$PATH python3 eZeeKonfigurator/functional_tests.py

pytest:
  stage: pytest
  before_script:
    - curl https://download.opensuse.org/repositories/security:/zeek/CentOS_8/security:zeek.repo -o /etc/yum.repos.d/zeek.repo
    - yum group install -y "Development Tools"
    - yum install -y zeekctl ${PYTHON_VERSION} ${PYTHON_VERSION}-devel
    - python3 -m venv test_env
    - test_env/bin/python3 -m pip install --upgrade pip setuptools wheel
    - test_env/bin/python3 setup.py install
  script:
    - PATH=/opt/zeek/bin:$PATH DJANGO_SETTINGS_MODULE=eZeeKonfigurator.settings.development test_env/bin/python3 manage.py migrate
    - PATH=/opt/zeek/bin:$PATH DJANGO_SETTINGS_MODULE=eZeeKonfigurator.settings.development test_env/bin/python3 manage.py test