# Generated by Django 2.2.4 on 2019-10-08 02:57

import django.db.models.deletion
from django.db import migrations, models

import webconfig.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerDaemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True,
                                                    verbose_name='The IP address Zeek clients should connect to')),
                ('port', models.PositiveIntegerField(blank=True, null=True,
                                                     verbose_name='The TCP port Zeek clients should connect to')),
                ('uuid', models.UUIDField()),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('authorized', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('namespace',
                 models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=256)),
                ('datatype', models.CharField(max_length=512)),
                ('docstring',
                 models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('uuid', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='ZeekAddr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True,
                                             help_text='What is this significance of the chosen value?',
                                             max_length=1024, null=True,
                                             verbose_name='Value comment')),
                ('v', models.GenericIPAddressField(verbose_name='IP address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZeekBool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True,
                                             help_text='What is this significance of the chosen value?',
                                             max_length=1024, null=True,
                                             verbose_name='Value comment')),
                ('v', models.BooleanField(verbose_name='True?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZeekContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True,
                                             help_text='What is this significance of the chosen value?',
                                             max_length=1024, null=True,
                                             verbose_name='Value comment')),
                ('ctr_type', models.CharField(
                    choices=[('s', 'set'), ('v', 'vector'), ('t', 'table'),
                             ('p', 'pattern')], max_length=1)),
                ('v', models.CharField(blank=True, max_length=1024, null=True,
                                       verbose_name='Current value')),
                ('type_name', models.CharField(max_length=512,
                                               verbose_name='How Zeek identifies the name, e.g. table[count, port] of string')),
                ('index_types',
                 models.CharField(blank=True, default='<unknown>',
                                  max_length=1024, null=True)),
                ('yield_type', models.CharField(blank=True, default='<unknown>',
                                                max_length=1024, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZeekContainerItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True,
                                             help_text='What is this significance of the chosen value?',
                                             max_length=1024, null=True,
                                             verbose_name='Value comment')),
                ('object_id',
                 models.PositiveIntegerField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(blank=True, null=True,
                                                         verbose_name='Position in the container, for those where order matters')),
                ('content_type', models.ForeignKey(blank=True, null=True,
                                                   on_delete=django.db.models.deletion.SET_NULL,
                                                   to='contenttypes.ContentType')),
                ('parent', models.ForeignKey(
                    help_text='The container value that we belong to',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='items', to='webconfig.ZeekContainer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZeekCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True,
                                             help_text='What is this significance of the chosen value?',
                                             max_length=1024, null=True,
                                             verbose_name='Value comment')),
                ('v_msb', models.BigIntegerField(default=0)),
                ('v_lsb', models.BigIntegerField()),
                ('v', models.CharField(max_length=20, validators=[
                    webconfig.models.validate_count], verbose_name='value')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZeekDouble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True,
                                             help_text='What is this significance of the chosen value?',
                                             max_length=1024, null=True,
                                             verbose_name='Value comment')),
                ('v', models.FloatField(verbose_name='value')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZeekEnum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True,
                                             help_text='What is this significance of the chosen value?',
                                             max_length=1024, null=True,
                                             verbose_name='Value comment')),
                ('v', models.CharField(max_length=1024, verbose_name='value')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZeekInt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True,
                                             help_text='What is this significance of the chosen value?',
                                             max_length=1024, null=True,
                                             verbose_name='Value comment')),
                ('v', models.BigIntegerField(verbose_name='Value')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZeekInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True,
                                             help_text='What is this significance of the chosen value?',
                                             max_length=1024, null=True,
                                             verbose_name='Value comment')),
                ('v', models.FloatField(verbose_name='Number of seconds')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZeekPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True,
                                             help_text='What is this significance of the chosen value?',
                                             max_length=1024, null=True,
                                             verbose_name='Value comment')),
                (
                'num', models.PositiveIntegerField(verbose_name='Port number')),
                ('proto', models.CharField(
                    choices=[('t', 'tcp'), ('u', 'udp'), ('i', 'icmp'),
                             ('?', 'unknown')], default='?', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZeekRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True,
                                             help_text='What is this significance of the chosen value?',
                                             max_length=1024, null=True,
                                             verbose_name='Value comment')),
                ('field_types', models.CharField(max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZeekString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True,
                                             help_text='What is this significance of the chosen value?',
                                             max_length=1024, null=True,
                                             verbose_name='Value comment')),
                ('v', models.CharField(blank=True, max_length=65536, null=True,
                                       verbose_name='value')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZeekSubnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True,
                                             help_text='What is this significance of the chosen value?',
                                             max_length=1024, null=True,
                                             verbose_name='Value comment')),
                ('v',
                 models.GenericIPAddressField(verbose_name='Network address')),
                ('cidr', models.PositiveSmallIntegerField(verbose_name='CIDR')),
                ('field', models.CharField(max_length=64,
                                           verbose_name='Subnet in CIDR notation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZeekTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True,
                                             help_text='What is this significance of the chosen value?',
                                             max_length=1024, null=True,
                                             verbose_name='Value comment')),
                ('v', models.DateTimeField(verbose_name='value')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZeekPattern',
            fields=[
                ('zeekcontainer_ptr', models.OneToOneField(auto_created=True,
                                                           on_delete=django.db.models.deletion.CASCADE,
                                                           parent_link=True,
                                                           primary_key=True,
                                                           serialize=False,
                                                           to='webconfig.ZeekContainer')),
            ],
            options={
                'abstract': False,
            },
            bases=('webconfig.zeekcontainer',),
        ),
        migrations.CreateModel(
            name='ZeekRecordField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True,
                                             help_text='What is this significance of the chosen value?',
                                             max_length=1024, null=True,
                                             verbose_name='Value comment')),
                ('name', models.CharField(max_length=1024)),
                ('val_type', models.CharField(max_length=1024)),
                ('docstring',
                 models.CharField(blank=True, max_length=1024, null=True)),
                ('index_pos', models.PositiveIntegerField()),
                ('record_elem_objid', models.PositiveIntegerField(null=True)),
                ('parent',
                 models.ForeignKey(help_text='The record we belong to',
                                   on_delete=django.db.models.deletion.CASCADE,
                                   related_name='fields',
                                   to='webconfig.ZeekRecord')),
                ('record_elem_ctype', models.ForeignKey(null=True,
                                                        on_delete=django.db.models.deletion.CASCADE,
                                                        related_name='record_elem',
                                                        to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZeekContainerKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True,
                                             help_text='What is this significance of the chosen value?',
                                             max_length=1024, null=True,
                                             verbose_name='Value comment')),
                ('index_offset', models.PositiveSmallIntegerField(
                    verbose_name="For composite keys, the 0-index position that we're in.")),
                ('object_id', models.PositiveIntegerField()),
                ('content_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='contenttypes.ContentType')),
                ('parent', models.ForeignKey(
                    help_text='The key-value pair that we belong to',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='keys', to='webconfig.ZeekContainerItem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='contenttypes.ContentType')),
                ('option',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='webconfig.Option')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=150)),
                ('uuid', models.UUIDField()),
                ('zeek_version', models.CharField(max_length=30)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                (
                'last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('authorized', models.BooleanField(blank=True, null=True)),
                ('groups', models.ManyToManyField(to='webconfig.SensorGroup')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='webconfig.Sensor'),
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_created=True)),
                ('msg', models.CharField(max_length=1024,
                                         verbose_name='Summary of the change. e.g. Increased timeout due to long-lived connections')),
                ('user', models.CharField(max_length=64)),
                ('options', models.ManyToManyField(to='webconfig.Option')),
            ],
        ),
    ]
