# Generated by Django 2.2.4 on 2019-08-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen', models.DateTimeField(auto_created=True)),
                ('hostname', models.CharField(max_length=150)),
                ('uuid', models.UUIDField()),
                ('zeek_version', models.CharField(max_length=30)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
