# Generated by Django 2.2.4 on 2019-09-27 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerDaemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='The IP address Zeek clients should connect to')),
                ('port', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='The TCP port Zeek clients should connect to')),
                ('uuid', models.UUIDField()),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('authorized', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=150)),
                ('uuid', models.UUIDField()),
                ('zeek_version', models.CharField(max_length=30)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('authorized', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='option',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webconfig.Sensor'),
        ),
        migrations.DeleteModel(
            name='ClientComponent',
        ),
    ]
