# Generated by Django 2.2.4 on 2019-08-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='first_seen',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
