# Generated by Django 2.2.4 on 2019-09-27 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrokerDaemon',
        ),
    ]
