# Generated by Django 2.2.4 on 2019-10-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zeeksubnet',
            name='field',
            field=models.CharField(default='', max_length=64, verbose_name='Subnet in CIDR notation'),
            preserve_default=False,
        ),
    ]
