# Generated by Django 2.2.4 on 2019-09-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0002_auto_20190927_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerdaemon',
            name='port',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='The TCP port Zeek clients should connect to'),
        ),
        migrations.AlterField(
            model_name='zeekport',
            name='num',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='zeektableindexelement',
            name='index_pos',
            field=models.PositiveIntegerField(),
        ),
    ]
