# Generated by Django 2.2.4 on 2019-08-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0002_auto_20190830_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensor',
            name='last_ip',
            field=models.GenericIPAddressField(default='1.1.1.1'),
            preserve_default=False,
        ),
    ]
