# Generated by Django 2.2.4 on 2019-09-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0002_auto_20190925_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zeektableval',
            name='yield_elem_objid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
