# Generated by Django 2.2.4 on 2019-09-25 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0003_auto_20190925_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zeektableval',
            name='index_types',
        ),
        migrations.RemoveField(
            model_name='zeektableval',
            name='yield_type',
        ),
    ]
