# Generated by Django 2.2.4 on 2019-08-30 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0003_auto_20190830_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='blocked',
        ),
    ]
