# Generated by Django 3.2.4 on 2021-07-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('webconfig', '0003_auto_20210630_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zeekport',
            name='proto',
            field=models.CharField(
                choices=[('t', 'tcp'), ('u', 'udp'), ('i', 'icmp'), ('?', '?')],
                default='?', max_length=1),
        ),
    ]
