# Generated by Django 2.2.4 on 2019-09-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0004_auto_20190929_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zeekport',
            name='proto',
            field=models.CharField(choices=[('t', 'tcp'), ('u', 'udp'), ('i', 'icmp'), ('?', 'unknown')], default='?', max_length=1),
        ),
    ]
