# Generated by Django 2.2.4 on 2019-08-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0004_remove_sensor_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='authorized',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
