# Generated by Django 2.2.4 on 2019-09-25 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0004_auto_20190925_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zeektableval',
            name='yield_elem_ctype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yield_elem', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='zeektableval',
            name='yield_elem_objid',
            field=models.PositiveIntegerField(),
        ),
    ]
