# Generated by Django 2.2.4 on 2019-08-30 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0006_option_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='sensor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webconfig.Sensor'),
            preserve_default=False,
        ),
    ]
