# Generated by Django 2.2.4 on 2019-09-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0010_zeekint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZeekDouble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
