# Generated by Django 2.2.4 on 2019-09-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0013_zeektime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZeekString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v', models.CharField(max_length=65536)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
