# Generated by Django 2.2.4 on 2019-09-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0017_zeekvector_zeekvectorelement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='docstring',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
