# Generated by Django 2.2.4 on 2019-09-24 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('webconfig', '0018_auto_20190924_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='zeekvectorelement',
            name='elem_ctype',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='elem', to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zeekvectorelement',
            name='elem_objid',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zeekvectorelement',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='zeekvectorelement',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
